function set_plot_property(fig, x_label, y_label, legend_label, plot_title, file_name, folder_name)
    set(gca,...
    'Units','normalized',...
    'FontUnits','points',...
    'FontWeight','normal',...
    'FontSize',7,...
    'FontName','Times');
    
    xlabel(x_label, ...
            'FontUnits','points',...
            'FontSize',8,...
            'FontName','Times');
    ylabel(y_label, ...
            'FontUnits','points',...
            'FontSize',9,...
            'FontName','Times');
    legend(legend_label,...
            'FontSize',7,...
            'FontName','Times',...
            'Location','NorthEast')
    
    title(plot_title, 'FontUnits','points', ... 
           'FontSize',10, 'FontName','Times', ...
           'FontWeight','normal');
    
    drawnow
    
    saveas(fig,strcat(folder_name,'/',file_name),'epsc')
    savefig(strcat(folder_name,'/',file_name,'.fig'))
end